### PR TITLE
fixed add to do form function

### LINKED ISSUE #20: Should be able to add to dos using form

### PR DESCRIPTION
**Pull request by bowssy88**
fixes #20

### CODE REVIEW

File: dom.js [hunk 1]
```diff
@@ -48,15 +48,17 @@
...
   if (addTodoForm) {
     addTodoForm.addEventListener('submit', function(event) {
-      // https://developer.mozilla.org/en-US/docs/Web/Events/submit
-      // what does event.preventDefault do?
-      // what is inside event.target?
 
-      var description = '?'; // event.target ....
+      event.preventDefault() ;
+      var newDescription = document.getElementById("add-todo").description.value ;
+        console.log("our way", newDescription);
```
Comment (rachaelcodes) [inline dom.js]: do you need this in the final code?
